---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.9.41

verifier: 
  name: inspec

platforms:
  - name: ubuntu-16.04

suites:
  - name: client
    run_list:
      - recipe[inspec-workshop-cookbook::default]
      - recipe[inspec-workshop-cookbook::client]
    attributes:  
    verifier:
      inspec_tests:
        - /Users/anniehedgpeth/chef_repo/profiles/practice-inspec-profile
  - name: server
    run_list:
      - recipe[inspec-workshop-cookbook::default]
      - recipe[inspec-workshop-cookbook::server]
    attributes:  
    verifier:
      inspec_tests:
        - /Users/anniehedgpeth/chef_repo/profiles/practice-inspec-profile
