---
driver:
  name: vagrant
# the thing that is setting up the VM

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.9.41
  client_rb:
    add_formatter: min

# sets the machine up the way it's programmed to be set up

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
verifier: 
  name: inspec
# runs tests

platforms:
  - name: centos-6.7
#image of a machine

suites:
  - name: default
    run_list:
      - recipe[inspec-workshop-cookbook::default]
# found in recipes folder
    attributes:  
    verifier:
      inspec_tests:
        - /Users/anniehedgpeth/inspec-workshop
#        - https://github.com/anniehedgpeth/inspec-workshop