name 'inspec-workshop-cookbook'
maintainer 'Annie Hedgpeth'
maintainer_email 'annie.hedgpeth@gmail.com'
license 'all_rights'
description 'Installs/Configures inspec-workshop-cookbook'
long_description 'Installs/Configures inspec-workshop-cookbook'
version '0.1.0'
